AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  MediaConvertRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - mediaconvert.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
      RoleName: MediaConvert_Default_Role
  ExtractAudioJobTemplate:
    Type: AWS::MediaConvert::JobTemplate
    Properties:
      Name: !Sub ${AWS::StackName}-ExtractAudioJobTemplate
      SettingsJson:
        OutputGroups:
          - Name: File Group
            Outputs:
              - ContainerSettings:
                  Container: RAW
                AudioDescriptions:
                  - AudioTypeControl: FOLLOW_INPUT
                    AudioSourceName: Audio Selector 1
                    CodecSettings:
                      Codec: MP3
                      Mp3Settings:
                        Bitrate: 192000
                        Channels: 2
                        RateControlMode: CBR
                        SampleRate: 48000
                    LanguageCodeControl: FOLLOW_INPUT
            OutputGroupSettings:
              Type: FILE_GROUP_SETTINGS
              FileGroupSettings:
                Destination: s3://s3-to-sdhs-test-afs25-mockincomingbucket/$fn$
        AdAvailOffset: 0
        Inputs:
          - AudioSelectors:
              Audio Selector 1:
                Offset: 0
                DefaultSelection: DEFAULT
                ProgramSelection: 1
            FilterEnable: AUTO
            PsiControl: USE_PSI
            FilterStrength: 0
            DeblockFilter: DISABLED
            DenoiseFilter: DISABLED
            TimecodeSource: EMBEDDED
  InterviewAudio:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-interview-audio
  FileTransferStatus:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-FileTransferStatus
  MonitorIncomingBucket:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-MonitorIncomingBucket
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: MonitorIncomingBucket
      CodeUri: src
      Handler: main.monitor_incoming_bucket
      Runtime: python3.7
      MemorySize: !Ref EnvConfiglambdamemorysizeAsString
      Timeout: !Ref EnvConfiglambdatimeoutAsString
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AmazonS3ReadOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTransferStatus
        - S3CrudPolicy:
            BucketName: !Ref MockIncomingBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ResearchProjects
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          TABLE_NAME: !Ref FileTransferStatus
          TABLE_ARN: !GetAtt FileTransferStatus.Arn
          BUCKET_NAME_2: !Ref MockIncomingBucket
          BUCKET_ARN_2: !GetAtt MockIncomingBucket.Arn
          TABLE_NAME_2: !Ref ResearchProjects
          TABLE_ARN_2: !GetAtt ResearchProjects.Arn
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(20 minutes)
          Metadata:
            StackeryName: MonitorIncomingBucketTimer
  MockIncomingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-mockincomingbucket
  ProcessIncomingFilesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CreateMediaConvertJob
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: mediaconvert:CreateJob
                Resource: '*'
        - PolicyName: PassMediaConvertRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/MediaConvert_Default_Role
      RoleName: !Sub ${AWS::StackName}-${AWS::Region}-${ResourceName}
  ProcessIncomingFiles:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-ProcessIncomingFiles
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: ProcessIncomingFiles
      CodeUri: src
      Handler: main.process_incoming_files
      Runtime: python3.7
      MemorySize: !Ref EnvConfiglambdamemorysizeAsString
      Timeout: !Ref EnvConfiglambdatimeoutAsString
      Tracing: Active
      Role: !GetAtt ProcessIncomingFilesExecutionRole.Arn
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTransferStatus
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Environment:
        Variables:
          TABLE_NAME: !Ref FileTransferStatus
          TABLE_ARN: !GetAtt FileTransferStatus.Arn
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
      Events:
        Timer2:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
          Metadata:
            StackeryName: ProcessIncomingFilesTimer
  TransferFile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-TransferFile
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: TransferFile
      CodeUri: src
      Handler: main.transfer_file
      Runtime: python3.7
      Timeout: 900
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AmazonS3ReadOnlyAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTransferStatus
      Environment:
        Variables:
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
          TABLE_NAME: !Ref FileTransferStatus
          TABLE_ARN: !GetAtt FileTransferStatus.Arn
      MemorySize: !Ref EnvConfiglambdamemorysizeAsString
      Events:
        InterviewAudio:
          Type: S3
          Properties:
            Bucket: !Ref InterviewAudio
            Events:
              - s3:ObjectCreated:*
  FileTransferAudit:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-FileTransferAudit
  ClearProcessed:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-ClearProcessed
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: ClearProcessed
      CodeUri: src
      Handler: main.clear_processed
      Runtime: python3.7
      MemorySize: !Ref EnvConfiglambdamemorysizeAsString
      Timeout: !Ref EnvConfiglambdatimeoutAsString
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTransferAudit
        - DynamoDBCrudPolicy:
            TableName: !Ref FileTransferStatus
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${EnvironmentTagName}/*
      Environment:
        Variables:
          TABLE_NAME: !Ref FileTransferAudit
          TABLE_ARN: !GetAtt FileTransferAudit.Arn
          TABLE_NAME_2: !Ref FileTransferStatus
          TABLE_ARN_2: !GetAtt FileTransferStatus.Arn
          SECRETS_NAMESPACE: !Sub /${EnvironmentTagName}/
      Events:
        Timer3:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
          Metadata:
            StackeryName: ClearProcessedTimer
  ResearchProjects:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-ResearchProjects
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfiglambdamemorysizeAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/lambda/memory-size
  EnvConfiglambdatimeoutAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/lambda/timeout
Metadata:
  EnvConfigParameters:
    EnvConfiglambdamemorysizeAsString: lambda.memory-size
    EnvConfiglambdatimeoutAsString: lambda.timeout